name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
assignees: ["shahmal1yev"]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Run command '...'
        2. Use lexicon file '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: input
    id: php-version
    attributes:
      label: PHP Version
      placeholder: "8.2.15"
    validations:
      required: true

  - type: textarea
    id: error-output
    attributes:
      label: Error Output
      description: Any error messages
      render: text

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Anything else relevant